theme: jekyll-theme-minimal

header_pages:
  - index.md
  - resume.md
  - contact.md

markdown: kramdown
plugins:
  - jekyll-feed

# Custom settings
email: membaye@uwaterloo.ca
linkedin: https://www.linkedin.com/in/matthewembaye/
github: https://github.com/membaye
